# Classifying Penguins with Keras

In [56]:
pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [57]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [58]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [59]:
pip install palmerpenguins

Requirement already satisfied: palmerpenguins in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (0.1.6)
Requirement already satisfied: pandas in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from palmerpenguins) (3.0.3)
Requirement already satisfied: numpy in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from palmerpenguins) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [60]:
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins = penguins.dropna()
penguins.head()
penguins = penguins.sample(frac=1, random_state=42).reset_index(drop=True)

In [61]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,3250.0,39.5,16.7,178.0,True,False
1,3675.0,50.9,17.9,196.0,True,False
2,4000.0,42.1,19.1,195.0,False,True
3,4850.0,46.6,14.2,210.0,True,False
4,4050.0,41.1,18.2,192.0,False,True
...,...,...,...,...,...,...
328,4750.0,49.6,15.0,216.0,False,True
329,3900.0,37.2,19.4,184.0,False,True
330,3200.0,39.7,17.7,193.0,True,False
331,3950.0,45.2,17.8,198.0,True,False
332,3175.0,38.1,17.0,181.0,True,False

In [62]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.152778,0.269091,0.428571,0.101695,1.0,0.0
1,0.270833,0.683636,0.571429,0.406780,1.0,0.0
2,0.361111,0.363636,0.714286,0.389831,0.0,1.0
3,0.597222,0.527273,0.130952,0.644068,1.0,0.0
4,0.375000,0.327273,0.607143,0.338983,0.0,1.0
...,...,...,...,...,...,...
328,0.569444,0.636364,0.226190,0.745763,0.0,1.0
329,0.333333,0.185455,0.750000,0.203390,0.0,1.0
330,0.138889,0.276364,0.547619,0.355932,1.0,0.0
331,0.347222,0.476364,0.559524,0.440678,1.0,0.0
332,0.131944,0.218182,0.464286,0.152542,1.0,0.0

In [63]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: str

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)

In [64]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [65]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [66]:
pip install pydot

Requirement already satisfied: pydot in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (4.0.1)
Requirement already satisfied: pyparsing>=3.1.0 in /opt/anaconda3/envs/tensorflow_env/lib/python3.11/site-packages (from pydot) (3.3.2)
Note: you may need to restart the kernel to use updated packages.

In [67]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [68]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.4816 - loss: 1.0959 - val_accuracy: 0.5882 - val_loss: 1.0933
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5251 - loss: 1.0902 - val_accuracy: 0.6176 - val_loss: 1.0881
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5753 - loss: 1.0859 - val_accuracy: 0.6176 - val_loss: 1.0835
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5953 - loss: 1.0819 - val_accuracy: 0.6176 - val_loss: 1.0792
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6355 - loss: 1.0782 - val_accuracy: 0.6471 - val_loss: 1.0747
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7324 - loss: 1.0720 - val_accuracy: 0.7647 - val_loss: 1.0671
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7659 - loss: 1.0647 - val_accuracy: 0.7353 - val_loss: 1.0600
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7559 - loss: 1.0587 - val_accuracy: 0.7353 - val_loss: 1.0535
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7458 - loss: 1.0531 - val_accuracy: 0.7353 - val_loss: 1.0469
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7324 - loss: 1.0472 - val_accuracy: 0.7353 - val_loss: 1.0391
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7358 - loss: 1.0415 - val_accuracy: 0.7353 - val_loss: 1.0320
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7258 - loss: 1.0365 - val_accuracy: 0.7353 - val_loss: 1.0261
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7258 - loss: 1.0319 - val_accuracy: 0.7353 - val_loss: 1.0212
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7157 - loss: 1.0271 - val_accuracy: 0.7353 - val_loss: 1.0166
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7090 - loss: 1.0225 - val_accuracy: 0.7647 - val_loss: 1.0126
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7324 - loss: 1.0179 - val_accuracy: 0.7647 - val_loss: 1.0068
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7324 - loss: 1.0134 - val_accuracy: 0.7647 - val_loss: 1.0016
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7358 - loss: 1.0085 - val_accuracy: 0.7647 - val_loss: 0.9968
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7391 - loss: 1.0035 - val_accuracy: 0.7647 - val_loss: 0.9907
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7492 - loss: 0.9985 - val_accuracy: 0.7941 - val_loss: 0.9861
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7525 - loss: 0.9933 - val_accuracy: 0.7647 - val_loss: 0.9795
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7492 - loss: 0.9879 - val_accuracy: 0.7647 - val_loss: 0.9736
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7492 - loss: 0.9828 - val_accuracy: 0.7647 - val_loss: 0.9677
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7492 - loss: 0.9770 - val_accuracy: 0.7941 - val_loss: 0.9621
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7525 - loss: 0.9715 - val_accuracy: 0.7941 - val_loss: 0.9561
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7458 - loss: 0.9666 - val_accuracy: 0.7941 - val_loss: 0.9504
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7559 - loss: 0.9602 - val_accuracy: 0.7941 - val_loss: 0.9447
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7559 - loss: 0.9546 - val_accuracy: 0.7941 - val_loss: 0.9377
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7559 - loss: 0.9483 - val_accuracy: 0.7941 - val_loss: 0.9309
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7592 - loss: 0.9418 - val_accuracy: 0.7941 - val_loss: 0.9262
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7625 - loss: 0.9356 - val_accuracy: 0.7941 - val_loss: 0.9182
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.9297 - val_accuracy: 0.7941 - val_loss: 0.9101
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7625 - loss: 0.9228 - val_accuracy: 0.7941 - val_loss: 0.9033
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7625 - loss: 0.9167 - val_accuracy: 0.7941 - val_loss: 0.8957
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7625 - loss: 0.9102 - val_accuracy: 0.7941 - val_loss: 0.8902
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.9035 - val_accuracy: 0.7941 - val_loss: 0.8825
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.8969 - val_accuracy: 0.7941 - val_loss: 0.8745
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.8901 - val_accuracy: 0.7941 - val_loss: 0.8667
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.8832 - val_accuracy: 0.7941 - val_loss: 0.8598
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.8764 - val_accuracy: 0.7941 - val_loss: 0.8506
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.8697 - val_accuracy: 0.7941 - val_loss: 0.8428
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.8628 - val_accuracy: 0.7941 - val_loss: 0.8352
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.8564 - val_accuracy: 0.7941 - val_loss: 0.8283
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7659 - loss: 0.8492 - val_accuracy: 0.7941 - val_loss: 0.8200
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7659 - loss: 0.8425 - val_accuracy: 0.7941 - val_loss: 0.8118
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7625 - loss: 0.8356 - val_accuracy: 0.7941 - val_loss: 0.8045
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.8288 - val_accuracy: 0.7941 - val_loss: 0.7965
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7625 - loss: 0.8220 - val_accuracy: 0.7941 - val_loss: 0.7889
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7625 - loss: 0.8154 - val_accuracy: 0.7941 - val_loss: 0.7826
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7625 - loss: 0.8086 - val_accuracy: 0.7941 - val_loss: 0.7760
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7692 - loss: 0.8022 - val_accuracy: 0.7941 - val_loss: 0.7675
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7957 - val_accuracy: 0.7941 - val_loss: 0.7594
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7893 - val_accuracy: 0.7941 - val_loss: 0.7519
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7625 - loss: 0.7828 - val_accuracy: 0.7941 - val_loss: 0.7457
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7767 - val_accuracy: 0.7941 - val_loss: 0.7394
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7704 - val_accuracy: 0.7941 - val_loss: 0.7333
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7645 - val_accuracy: 0.7941 - val_loss: 0.7259
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7587 - val_accuracy: 0.7941 - val_loss: 0.7182
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7528 - val_accuracy: 0.7941 - val_loss: 0.7120
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7472 - val_accuracy: 0.7941 - val_loss: 0.7054
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7414 - val_accuracy: 0.7941 - val_loss: 0.7008
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7659 - loss: 0.7357 - val_accuracy: 0.7941 - val_loss: 0.6930
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7304 - val_accuracy: 0.7941 - val_loss: 0.6882
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7252 - val_accuracy: 0.7941 - val_loss: 0.6814
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7198 - val_accuracy: 0.7941 - val_loss: 0.6758
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7148 - val_accuracy: 0.7941 - val_loss: 0.6699
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7097 - val_accuracy: 0.7941 - val_loss: 0.6654
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.7045 - val_accuracy: 0.7941 - val_loss: 0.6614
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.6992 - val_accuracy: 0.7941 - val_loss: 0.6546
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7692 - loss: 0.6942 - val_accuracy: 0.7941 - val_loss: 0.6479
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.6904 - val_accuracy: 0.7941 - val_loss: 0.6448
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7692 - loss: 0.6852 - val_accuracy: 0.7941 - val_loss: 0.6386
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7659 - loss: 0.6812 - val_accuracy: 0.7941 - val_loss: 0.6372
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7692 - loss: 0.6776 - val_accuracy: 0.7941 - val_loss: 0.6317
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7659 - loss: 0.6732 - val_accuracy: 0.7941 - val_loss: 0.6286
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7759 - loss: 0.6692 - val_accuracy: 0.7941 - val_loss: 0.6234
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7726 - loss: 0.6653 - val_accuracy: 0.7941 - val_loss: 0.6202
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7726 - loss: 0.6617 - val_accuracy: 0.7941 - val_loss: 0.6163
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7759 - loss: 0.6578 - val_accuracy: 0.7941 - val_loss: 0.6119
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7759 - loss: 0.6541 - val_accuracy: 0.7941 - val_loss: 0.6069
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7692 - loss: 0.6505 - val_accuracy: 0.7941 - val_loss: 0.6034
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7759 - loss: 0.6468 - val_accuracy: 0.7941 - val_loss: 0.5993
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7759 - loss: 0.6433 - val_accuracy: 0.7941 - val_loss: 0.5968
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7759 - loss: 0.6398 - val_accuracy: 0.7941 - val_loss: 0.5929
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7759 - loss: 0.6368 - val_accuracy: 0.7941 - val_loss: 0.5895
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7759 - loss: 0.6332 - val_accuracy: 0.7941 - val_loss: 0.5875
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7793 - loss: 0.6298 - val_accuracy: 0.7941 - val_loss: 0.5830
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7759 - loss: 0.6267 - val_accuracy: 0.7941 - val_loss: 0.5802
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7759 - loss: 0.6237 - val_accuracy: 0.7941 - val_loss: 0.5774
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7826 - loss: 0.6208 - val_accuracy: 0.7941 - val_loss: 0.5735
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7793 - loss: 0.6181 - val_accuracy: 0.7941 - val_loss: 0.5717
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7793 - loss: 0.6155 - val_accuracy: 0.7941 - val_loss: 0.5694
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7826 - loss: 0.6123 - val_accuracy: 0.7941 - val_loss: 0.5664
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7793 - loss: 0.6096 - val_accuracy: 0.7941 - val_loss: 0.5661
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7860 - loss: 0.6073 - val_accuracy: 0.7941 - val_loss: 0.5618
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7860 - loss: 0.6046 - val_accuracy: 0.7941 - val_loss: 0.5585
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7860 - loss: 0.6022 - val_accuracy: 0.7941 - val_loss: 0.5560
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7826 - loss: 0.5997 - val_accuracy: 0.7941 - val_loss: 0.5548
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7793 - loss: 0.5976 - val_accuracy: 0.7941 - val_loss: 0.5520
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7860 - loss: 0.5949 - val_accuracy: 0.7941 - val_loss: 0.5496
11/11 - 0s - 3ms/step - accuracy: 0.7868 - loss: 0.5887

In [73]:
model_logit_false = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_false.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_false = model_logit_false.fit(scaled_penguins_x, penguins_y, batch_size = 50, epochs = 60, validation_split = 0.3)

scores = model_logit_false.evaluate(scaled_penguins_x, penguins_y, verbose = 5)

Epoch 1/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.7854 - loss: 0.5165 - val_accuracy: 0.8000 - val_loss: 0.4650
Epoch 2/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7897 - loss: 0.5129 - val_accuracy: 0.8000 - val_loss: 0.4641
Epoch 3/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7897 - loss: 0.5104 - val_accuracy: 0.8000 - val_loss: 0.4623
Epoch 4/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7897 - loss: 0.5080 - val_accuracy: 0.8000 - val_loss: 0.4592
Epoch 5/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7897 - loss: 0.5068 - val_accuracy: 0.8000 - val_loss: 0.4591
Epoch 6/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7854 - loss: 0.5052 - val_accuracy: 0.8000 - val_loss: 0.4590
Epoch 7/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7897 - loss: 0.5031 - val_accuracy: 0.8000 - val_loss: 0.4548
Epoch 8/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7897 - loss: 0.5019 - val_accuracy: 0.8000 - val_loss: 0.4541
Epoch 9/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7897 - loss: 0.5001 - val_accuracy: 0.8000 - val_loss: 0.4527
Epoch 10/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7897 - loss: 0.4985 - val_accuracy: 0.8000 - val_loss: 0.4516
Epoch 11/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7897 - loss: 0.4965 - val_accuracy: 0.8000 - val_loss: 0.4508
Epoch 12/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7897 - loss: 0.4959 - val_accuracy: 0.8000 - val_loss: 0.4486
Epoch 13/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7940 - loss: 0.4933 - val_accuracy: 0.8000 - val_loss: 0.4479
Epoch 14/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7940 - loss: 0.4916 - val_accuracy: 0.8000 - val_loss: 0.4475
Epoch 15/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7897 - loss: 0.4899 - val_accuracy: 0.8000 - val_loss: 0.4455
Epoch 16/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7940 - loss: 0.4883 - val_accuracy: 0.8000 - val_loss: 0.4438
Epoch 17/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7983 - loss: 0.4867 - val_accuracy: 0.8100 - val_loss: 0.4412
Epoch 18/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8069 - loss: 0.4847 - val_accuracy: 0.8100 - val_loss: 0.4396
Epoch 19/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8026 - loss: 0.4833 - val_accuracy: 0.8100 - val_loss: 0.4385
Epoch 20/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8069 - loss: 0.4806 - val_accuracy: 0.8100 - val_loss: 0.4375
Epoch 21/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8026 - loss: 0.4800 - val_accuracy: 0.8100 - val_loss: 0.4345
Epoch 22/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8026 - loss: 0.4772 - val_accuracy: 0.8100 - val_loss: 0.4327
Epoch 23/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8112 - loss: 0.4752 - val_accuracy: 0.8300 - val_loss: 0.4292
Epoch 24/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8026 - loss: 0.4750 - val_accuracy: 0.8400 - val_loss: 0.4284
Epoch 25/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8069 - loss: 0.4717 - val_accuracy: 0.8300 - val_loss: 0.4261
Epoch 26/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8112 - loss: 0.4706 - val_accuracy: 0.8300 - val_loss: 0.4242
Epoch 27/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8069 - loss: 0.4683 - val_accuracy: 0.8400 - val_loss: 0.4230
Epoch 28/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8112 - loss: 0.4674 - val_accuracy: 0.8300 - val_loss: 0.4204
Epoch 29/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8112 - loss: 0.4645 - val_accuracy: 0.8400 - val_loss: 0.4191
Epoch 30/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8069 - loss: 0.4623 - val_accuracy: 0.8400 - val_loss: 0.4192
Epoch 31/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8155 - loss: 0.4610 - val_accuracy: 0.8400 - val_loss: 0.4162
Epoch 32/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8155 - loss: 0.4588 - val_accuracy: 0.8300 - val_loss: 0.4135
Epoch 33/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8155 - loss: 0.4571 - val_accuracy: 0.8400 - val_loss: 0.4137
Epoch 34/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8197 - loss: 0.4553 - val_accuracy: 0.8300 - val_loss: 0.4114
Epoch 35/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8197 - loss: 0.4530 - val_accuracy: 0.8400 - val_loss: 0.4099
Epoch 36/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8240 - loss: 0.4515 - val_accuracy: 0.8500 - val_loss: 0.4092
Epoch 37/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8240 - loss: 0.4496 - val_accuracy: 0.8500 - val_loss: 0.4073
Epoch 38/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8283 - loss: 0.4474 - val_accuracy: 0.8400 - val_loss: 0.4052
Epoch 39/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8326 - loss: 0.4459 - val_accuracy: 0.8600 - val_loss: 0.4047
Epoch 40/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8326 - loss: 0.4437 - val_accuracy: 0.8400 - val_loss: 0.4015
Epoch 41/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8369 - loss: 0.4420 - val_accuracy: 0.8600 - val_loss: 0.4015
Epoch 42/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8412 - loss: 0.4407 - val_accuracy: 0.8500 - val_loss: 0.3988
Epoch 43/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8369 - loss: 0.4382 - val_accuracy: 0.8400 - val_loss: 0.3967
Epoch 44/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8498 - loss: 0.4374 - val_accuracy: 0.8600 - val_loss: 0.3960
Epoch 45/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8455 - loss: 0.4353 - val_accuracy: 0.8500 - val_loss: 0.3938
Epoch 46/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8584 - loss: 0.4324 - val_accuracy: 0.8600 - val_loss: 0.3941
Epoch 47/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8498 - loss: 0.4312 - val_accuracy: 0.8600 - val_loss: 0.3918
Epoch 48/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8541 - loss: 0.4291 - val_accuracy: 0.8500 - val_loss: 0.3898
Epoch 49/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8670 - loss: 0.4273 - val_accuracy: 0.8600 - val_loss: 0.3870
Epoch 50/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8670 - loss: 0.4258 - val_accuracy: 0.8500 - val_loss: 0.3870
Epoch 51/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8627 - loss: 0.4241 - val_accuracy: 0.8700 - val_loss: 0.3885
Epoch 52/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8584 - loss: 0.4218 - val_accuracy: 0.8600 - val_loss: 0.3838
Epoch 53/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8627 - loss: 0.4199 - val_accuracy: 0.8700 - val_loss: 0.3871
Epoch 54/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8841 - loss: 0.4184 - val_accuracy: 0.8500 - val_loss: 0.3816
Epoch 55/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8670 - loss: 0.4170 - val_accuracy: 0.8700 - val_loss: 0.3816
Epoch 56/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8884 - loss: 0.4148 - val_accuracy: 0.8600 - val_loss: 0.3780
Epoch 57/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8712 - loss: 0.4130 - val_accuracy: 0.8600 - val_loss: 0.3773
Epoch 58/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8755 - loss: 0.4117 - val_accuracy: 0.8700 - val_loss: 0.3761
Epoch 59/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8755 - loss: 0.4102 - val_accuracy: 0.8600 - val_loss: 0.3745
Epoch 60/60
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8755 - loss: 0.4083 - val_accuracy: 0.8700 - val_loss: 0.3747

Dropping NAs, changing to 'softmax', shuffling my dataset, and then scaling down the batch size, making minimal changes to the parameters, gave me a higher accuracy than the last one I had.

In [70]:
model_logit_false.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

array([[6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [9.75183398e-02, 2.92981356e-01, 6.09500229e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.64890604e-04, 4.04551104e-02, 9.59380031e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.78182268e-01, 3.23522925e-01, 3.98294896e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [3.47726629e-04, 5.23345359e-02, 9.47317660e-01],
       [2.57308220e-05, 2.11542137e-02, 9.78819966e-01],
       [8.46748007e-04, 7.09077045e-02, 9.28245604e-01],
       [3.61965686e-01, 3.12205017e-01, 3.25829238e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.43900049e-01, 2.92728752e-01, 2.63371289e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.68108381e-04, 4.07268777e-02, 9.59105074e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.95938462e-01, 3.21988910e-01, 3.82072657e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.87304139e-02, 2.72068202e-01, 6.59201384e-01],
       [6.88973887e-05, 2.98645683e-02, 9.70066547e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [8.59527790e-05, 3.22592892e-02, 9.67654765e-01],
       [2.71007389e-01, 3.23992312e-01, 4.05000329e-01],
       [1.97407589e-05, 1.92737039e-02, 9.80706513e-01],
       [4.52487141e-01, 2.90285587e-01, 2.57227302e-01],
       [4.12030640e-04, 5.54720610e-02, 9.44115877e-01],
       [2.71127373e-01, 3.23985219e-01, 4.04887408e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [7.87252709e-02, 2.80402303e-01, 6.40872538e-01],
       [5.87078035e-01, 2.43439972e-01, 1.69481874e-01],
       [4.86924080e-03, 1.26628146e-01, 8.68502676e-01],
       [5.32218546e-05, 2.72892620e-02, 9.72657561e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.32266126e-04, 3.74770388e-02, 9.62390661e-01],
       [1.60692245e-04, 4.00951728e-02, 9.59744155e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [5.55387557e-01, 2.55838186e-01, 1.88774318e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.56972155e-01, 3.16044301e-01, 5.26983500e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.02459198e-04, 3.42941061e-02, 9.65603471e-01],
       [2.55737657e-04, 4.70823385e-02, 9.52661872e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [7.26178754e-04, 6.73076361e-02, 9.31966245e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.68179574e-05, 2.14637611e-02, 9.78509426e-01],
       [2.56189214e-05, 2.11218670e-02, 9.78852510e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.18787417e-01, 3.24416876e-01, 4.56795692e-01],
       [3.54488164e-01, 3.13604385e-01, 3.31907451e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.83152401e-01, 3.23145866e-01, 3.93701673e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.42689794e-04, 3.84768061e-02, 9.61380482e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.62768507e-05, 2.94630323e-02, 9.70470667e-01],
       [1.82893991e-01, 3.20991784e-01, 4.96114194e-01],
       [2.89135816e-04, 4.91164364e-02, 9.50594366e-01],
       [3.42696876e-04, 5.20732068e-02, 9.47584093e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [7.77875888e-04, 6.88974857e-02, 9.30324614e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [7.88115314e-04, 6.92037940e-02, 9.30008113e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [8.05851596e-06, 1.40583916e-02, 9.85933602e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [5.21956347e-02, 2.54761875e-01, 6.93042517e-01],
       [2.85692373e-03, 1.06451921e-01, 8.90691161e-01],
       [1.22333935e-04, 3.64746228e-02, 9.63403165e-01],
       [7.55271540e-05, 3.08373831e-02, 9.69087124e-01],
       [4.06079501e-01, 3.02616179e-01, 2.91304380e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [8.00713533e-05, 3.14720981e-02, 9.68447864e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.04655483e-01, 3.23485404e-01, 4.71859127e-01],
       [1.11676633e-01, 3.00409466e-01, 5.87913930e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.74452143e-04, 4.12527174e-02, 9.58572805e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [5.77096835e-05, 2.80725043e-02, 9.71869767e-01],
       [9.07471913e-05, 3.28750834e-02, 9.67034042e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [3.55196971e-04, 5.27180173e-02, 9.46926892e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [9.13547501e-02, 2.89238155e-01, 6.19407058e-01],
       [4.07103479e-01, 3.02367896e-01, 2.90528655e-01],
       [7.54711800e-04, 6.81942552e-02, 9.31051075e-01],
       [6.21751024e-05, 2.88130455e-02, 9.71124828e-01],
       [1.22967089e-04, 3.65401022e-02, 9.63336945e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.65611200e-04, 4.05162759e-02, 9.59318161e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.83566946e-05, 2.63895001e-02, 9.73562181e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [7.44215795e-05, 3.06791700e-02, 9.69246447e-01],
       [5.45924067e-01, 2.59383410e-01, 1.94692492e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.87589571e-02, 2.72093982e-01, 6.59146965e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [9.54794268e-06, 1.49248233e-02, 9.85065699e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [7.59005416e-05, 3.08904629e-02, 9.69033659e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.03055446e-04, 4.34777662e-02, 9.56319153e-01],
       [5.97952247e-01, 2.39001811e-01, 1.63045883e-01],
       [5.43076456e-01, 2.60435849e-01, 1.96487650e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.53179200e-05, 2.57969331e-02, 9.74157751e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [5.13226464e-02, 2.53693432e-01, 6.94983840e-01],
       [3.44040425e-04, 5.21432646e-02, 9.47512686e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.14597647e-04, 4.43165228e-02, 9.55468953e-01],
       [1.59961730e-01, 3.16739500e-01, 5.23298860e-01],
       [6.11093492e-05, 2.86395550e-02, 9.71299291e-01],
       [1.00740392e-04, 3.40928137e-02, 9.65806425e-01],
       [3.00466694e-04, 4.97707166e-02, 9.49928880e-01],
       [2.33918381e-05, 2.04579625e-02, 9.79518592e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.63654064e-05, 2.94767767e-02, 9.70456839e-01],
       [1.91235554e-03, 9.32204574e-02, 9.04867172e-01],
       [8.08844998e-05, 3.15831527e-02, 9.68335986e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.93663014e-04, 5.90125397e-02, 9.40493762e-01],
       [1.29900302e-03, 8.19180980e-02, 9.16782975e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [3.15032184e-01, 3.19786549e-01, 3.65181178e-01],
       [3.63928169e-01, 3.11826468e-01, 3.24245453e-01],
       [1.11024641e-01, 3.00099641e-01, 5.88875711e-01],
       [3.27109214e-04, 5.12466766e-02, 9.48426247e-01],
       [1.86693709e-04, 4.22326140e-02, 9.57580686e-01],
       [1.98247944e-04, 4.31190394e-02, 9.56682682e-01],
       [5.72855293e-04, 6.20878115e-02, 9.37339306e-01],
       [6.79778532e-05, 2.97248345e-02, 9.70207214e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.01453382e-04, 4.33588624e-02, 9.56439674e-01],
       [2.19714999e-01, 3.24460685e-01, 4.55824316e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [3.15848649e-01, 3.19680333e-01, 3.64471048e-01],
       [4.21934187e-01, 2.98648715e-01, 2.79417127e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [3.86981905e-01, 3.07037979e-01, 3.05980146e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [7.43731973e-04, 6.78557977e-02, 9.31400418e-01],
       [3.39929909e-01, 3.16126972e-01, 3.43943208e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.03941956e-03, 7.59964436e-02, 9.22964156e-01],
       [9.59926620e-05, 3.35247219e-02, 9.66379344e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [5.10918796e-01, 2.71851838e-01, 2.17229381e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.02696222e-01, 3.03428441e-01, 2.93875337e-01],
       [5.02448738e-01, 2.74712503e-01, 2.22838730e-01],
       [4.49156651e-05, 2.57165544e-02, 9.74238515e-01],
       [5.57878435e-01, 2.54892915e-01, 1.87228695e-01],
       [9.56246149e-05, 3.34799290e-02, 9.66424465e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.82984682e-05, 2.97736917e-02, 9.70158041e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.12473013e-05, 2.86621246e-02, 9.71276641e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.56421411e-05, 1.77590400e-02, 9.82225299e-01],
       [4.88014757e-06, 1.17771905e-02, 9.88217831e-01],
       [3.93878436e-05, 2.45607831e-02, 9.75399792e-01],
       [2.61209428e-01, 3.24485272e-01, 4.14305270e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.27643967e-05, 2.89081298e-02, 9.71029103e-01],
       [1.62038719e-04, 4.02112752e-02, 9.59626675e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.84702322e-01, 3.21252286e-01, 4.94045377e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.16722055e-05, 1.99164804e-02, 9.80061769e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.95106071e-01, 2.77141958e-01, 2.27752030e-01],
       [5.08900285e-01, 2.72539228e-01, 2.18560562e-01],
       [4.03498530e-01, 3.03236902e-01, 2.93264508e-01],
       [5.33017516e-01, 2.64099956e-01, 2.02882618e-01],
       [6.08501578e-05, 2.85970699e-02, 9.71342027e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.40924419e-04, 4.61231545e-02, 9.53635991e-01],
       [3.75361960e-05, 2.41499469e-02, 9.75812435e-01],
       [5.88687658e-01, 2.42789000e-01, 1.68523431e-01],
       [7.51805434e-04, 6.81050122e-02, 9.31143105e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.16345997e-03, 7.89389908e-02, 9.19897497e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.61900796e-04, 4.01994251e-02, 9.59638715e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.68780186e-05, 2.14806236e-02, 9.78492439e-01],
       [6.38664216e-02, 2.67490268e-01, 6.68643236e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.81893182e-01, 2.81393617e-01, 2.36713201e-01],
       [7.75395718e-04, 6.88228682e-02, 9.30401742e-01],
       [1.45097002e-01, 3.12921256e-01, 5.41981697e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.41486591e-05, 2.55619753e-02, 9.74393964e-01],
       [2.84845970e-04, 4.88642678e-02, 9.50850844e-01],
       [4.29365282e-05, 2.53140684e-02, 9.74643052e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.57507462e-03, 8.73808116e-02, 9.11044061e-01],
       [1.38493290e-03, 8.36976022e-02, 9.14917409e-01],
       [2.71534154e-05, 2.15576179e-02, 9.78415191e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [5.41060348e-04, 6.08898439e-02, 9.38569069e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.21163403e-04, 6.38248473e-02, 9.35553908e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.41991520e-04, 5.68220913e-02, 9.42735910e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.53170419e-01, 2.90088147e-01, 2.56741464e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.97260791e-04, 4.95873019e-02, 9.50115383e-01],
       [2.12006807e-01, 3.24032873e-01, 4.63960379e-01],
       [2.91575736e-04, 4.92587537e-02, 9.50449705e-01],
       [2.39154790e-04, 4.60059457e-02, 9.53754842e-01],
       [1.34888600e-04, 3.77333425e-02, 9.62131798e-01],
       [8.99916589e-02, 2.88363367e-01, 6.21644855e-01],
       [8.40748427e-04, 7.07371235e-02, 9.28422213e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.58787066e-01, 3.24579924e-01, 4.16633070e-01],
       [4.51317102e-01, 2.90622681e-01, 2.58060277e-01],
       [1.20148284e-03, 7.97977224e-02, 9.19000804e-01],
       [8.28152115e-05, 3.18439230e-02, 9.68073249e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [5.38851600e-05, 2.74076872e-02, 9.72538471e-01],
       [9.38394296e-05, 3.32609601e-02, 9.66645241e-01],
       [5.50908881e-05, 2.76205409e-02, 9.72324431e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [8.79956526e-04, 7.18373954e-02, 9.27282631e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.60567521e-04, 4.00843956e-02, 9.59755003e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.95382061e-04, 5.90827055e-02, 9.40421999e-01],
       [3.91453104e-05, 2.45077088e-02, 9.75453138e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [3.99761409e-01, 3.04123074e-01, 2.96115428e-01],
       [4.38327261e-05, 2.54978016e-02, 9.74458337e-01],
       [2.08778381e-01, 3.23809624e-01, 4.67411995e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [3.63377571e-01, 3.11933100e-01, 3.24689299e-01],
       [1.34988994e-04, 3.77430916e-02, 9.62121844e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.92331014e-05, 2.99152676e-02, 9.70015526e-01],
       [6.69294459e-05, 2.95639988e-02, 9.70369101e-01],
       [9.16253477e-02, 2.89409727e-01, 6.18964851e-01],
       [4.79074137e-04, 5.84103875e-02, 9.41110611e-01],
       [1.64266850e-03, 8.86159986e-02, 9.09741342e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [8.63912501e-05, 3.23165283e-02, 9.67597067e-01],
       [4.10709967e-04, 5.54110706e-02, 9.44178164e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.32530346e-03, 8.24711397e-02, 9.16203558e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.95621769e-04, 6.63315132e-02, 9.32972908e-01],
       [3.87218088e-01, 3.06985766e-01, 3.05796206e-01],
       [1.76220798e-04, 4.13970575e-02, 9.58426774e-01],
       [2.38077119e-01, 3.24920267e-01, 4.37002569e-01],
       [6.72617462e-05, 2.96151470e-02, 9.70317543e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.90444785e-04, 4.25242856e-02, 9.57285225e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.48231265e-04, 3.89887057e-02, 9.60862994e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [1.65843636e-01, 3.18007380e-01, 5.16148925e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [4.29704611e-04, 5.62761165e-02, 9.43294227e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01],
       [2.32549846e-01, 3.24861288e-01, 4.42588925e-01],
       [6.00761473e-01, 2.37840191e-01, 1.61398351e-01]], dtype=float32)

In [71]:
penguins['species']

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: str

In [72]:
penguins_y

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)